# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: baseline     # Name of the pipeline resource
    source: Baseline Image # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - main

variables:
- group: Non-Production

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PackerBuild@1
  displayName: Build Image in Azure
  continueOnError: true
  inputs:
    templateType: 'custom'
    customTemplateLocation: 'apache-image/packer.json'
    customTemplateParameters: |
      {
          "client_id": "$(CLIENT_ID)",
          "client_secret": "$(CLIENT_SECRET)",
          "tenant_id": "$(TENANT_ID)",
          "subscription_id": "$(SUBSCRIPTION_ID)",
          "image_resource_group": "$(IMAGE_RESOURCE_GROUP)",
          "image_name": "$(IMAGE_NAME)",
          "image_version": "$(IMAGE_VERSION)",
          "temp_resource_group_name": "$(TEMP_RESOURCE_GROUP_NAME)",
          "location": "$(LOCATION)"
      }
- task: AzureCLI@2
  displayName: Deploy Image to Azure Shared Image Gallery
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(c843b536-4aa0-45fc-868d-2a0913602b18)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az sig image-definition create -g rg-packer --gallery-name Gallery --gallery-image-definition RHEL-Apache --publisher RedHat --offer Apache --sku 8.2 --os-type Linux --os-state generalized
      az sig image-version create --resource-group RG-PACKER --gallery-name Gallery --gallery-image-definition RHEL-Apache --gallery-image-version 1.0.0 --managed-image "/subscriptions/c843b536-4aa0-45fc-868d-2a0913602b18/resourceGroups/rg-packer/providers/Microsoft.Compute/images/RHEL-Apache"