name: Build Azure AD Auth Demo

on:
  push:
    branches: main
    paths: 'app-services/azure-ad-auth/**'      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups
    
      - name: Build ASP.Net Core
        run: |
          cd chapter1/TodoListAPI
          dotnet add package Microsoft.ApplicationInsights --version 2.17.0
          dotnet build --configuration Release /property:GenerateFullPaths=true
          cd bin/Release/netcoreapp3.1
          zip -r aspnetcore.zip *
          
      - name: Build Angular
        run: |
          cd chapter1/TodoListSPA
          npm install
          npm install @angular/cli
          export PATH=node_modules/.bin:$PATH
          ng build
          cd dist/
          zip -r angular.zip * 
          
      - name: Update Release
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/39129460/assets/aspnetcore.zip
            
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/39129460/assets/angular.zip
            
          curl -X POST --data-binary @chapter1/TodoListAPI/bin/Release/netcoreapp3.1/aspnetcore.zip \
            -H "Content-Type: application/zip" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://uploads.github.com/repos/${{ github.repository }}/releases/39129460/assets?name=aspnetcore.zip
            
          curl -X POST --data-binary @chapter1/TodoListSPA/dist/angular.zip \
            -H "Content-Type: application/zip" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://uploads.github.com/repos/${{ github.repository }}/releases/39129460/assets?name=angular.zip

