# For more info on Python, GitHub Actions, and Azure App Service 
# please head to https://aka.ms/python-webapps-actions

name: Build and deploy Django app to Azure App Service

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

env:
  WEBAPP_NAME: 'python-django-demo'  # Replace with the name of your Azure web app
  PYTHON_VERSION: 3.8
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  AZURE_STORAGE_ACCOUNT_NAME: '${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}'
  AZURE_STORAGE_ACCOUNT_KEY: '${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static
      run: python manage.py collectstatic --no-input

    - name: Run tests
      run: python manage.py test
        
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
  
    - name: Disable static collection and set migration command on App Service
      uses: Azure/appservice-settings@v1
      with:  
        app-name: ${{ env.WEBAPP_NAME }}
        app-settings-json: '[{ "name": "AZURE_STORAGE_ACCOUNT_NAME", "value": "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" }, { "name": "AZURE_STORAGE_ACCOUNT_KEY", "value": "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" }, { "name": "DBHOST", "value": "${{ secrets.DBHOST }}"}, { "name": "DBNAME", "value": "${{ secrets.DBNAME }}"}, { "name": "DBUSER", "value": "${{ secrets.DBUSER }}"}, { "name": "DBPASS", "value": "${{ secrets.DBPASS }}"}, { "name": "DISABLE_COLLECTSTATIC", "value": "true" }, { "name": "POST_BUILD_COMMAND",  "value": "python manage.py makemigrations && python manage.py migrate" }, { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }]'

    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME}}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: .
