# For more info on Python, GitHub Actions, and Azure App Service 
# please head to https://aka.ms/python-webapps-actions

name: Deploy Django App

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: python-django

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Django
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd python-django
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
      
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      id: deploy
      with:
        scope: resourcegroup
        region: ${{ secrets.LOCATION }}
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        # Provide the name of a resource group, only required for resource Group deployments.
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: python-django/azureDeploy.json
        deploymentMode: Incremental
        deploymentName: GitHub
        parameters: resourceName=ral
  
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.deploy.outputs.appName }}
        package: .
